http_listen: 127.0.0.1:18080
va_addr: 127.0.0.1:55051
vsm_addr: 127.0.0.1:55051
restream:
  rtsp_base: "rtsp://127.0.0.1:8554/"
security:
  cors:
    allowed_origins: ["*"]
  auth:
    bearer_token: ""
  rate_limit:
    rps: 0
va:
  tls:
    enabled: true
    root_cert_file: controlplane/config/certs/ca.pem
    client_cert_file: controlplane/config/certs/cp_client.crt
    client_key_file: controlplane/config/certs/cp_client.key
vsm:
  tls:
    enabled: true
    root_cert_file: controlplane/config/certs/ca.pem
    client_cert_file: controlplane/config/certs/cp_client.crt
    client_key_file: controlplane/config/certs/cp_client.key
