name: "yolo_nms"
backend: "python"
max_batch_size: 8

input [
  { name: "raw" data_type: TYPE_FP32 dims: [ -1, 84 ] }
]
output [
  { name: "dets" data_type: TYPE_FP32 dims: [ -1, 7 ] }
]

parameters: {
  key: "conf"
  value: { string_value: "0.25" }
}
parameters: {
  key: "iou"
  value: { string_value: "0.45" }
}

