analyzer:
  multistage:
    nodes:
      - name: pre
        type: preproc.letterbox
        params: { out_w: "640", out_h: "640", use_cuda: "1" }
      - name: det
        type: model.ort
        params: { in: "tensor:det_input", outs: "tensor:det_raw", model_path: "D:/Projects/ai/cv/video-analyzer/build-ninja/bin/model/yolov12x.onnx" }
      - name: nms
        type: post.yolo.nms
        params: { conf: "0.65", iou: "0.45" }
      - name: ovl
        type: overlay.cuda
        params: { alpha: "0.2", thickness: "3" }
    edges:
      - [pre, det]
      - [det, nms]
      - [nms, ovl]

