models:
  det:
    yolo:
      v12l:
        onnx: "models/yolov12l.onnx"
        defaults:
          confidence_threshold: 0.25
          nms_threshold: 0.45
        input_width: 640
        input_height: 640
      v12x:
        onnx: "models/yolov12x.onnx"
        defaults:
          confidence_threshold: 0.25
          nms_threshold: 0.45
        input_width: 640
        input_height: 640
      v8n:
        onnx: "models/yolov8n.onnx"
        defaults:
          confidence_threshold: 0.25
          nms_threshold: 0.45
        input_width: 640
        input_height: 640
  seg:
    yolo:
      v12s_seg:
        onnx: "models/yolov12s-seg.onnx"
        defaults:
          confidence_threshold: 0.25
          nms_threshold: 0.45
          mask_threshold: 0.5
        input_width: 640
        input_height: 640
      v8s_seg:
        onnx: "models/yolov8s-seg.onnx"
        defaults:
          confidence_threshold: 0.25
          nms_threshold: 0.45
          mask_threshold: 0.5
        input_width: 640
        input_height: 640
