name: "preproc_letterbox"
backend: "python"
max_batch_size: 8

input [
  { name: "rgb8" data_type: TYPE_UINT8 dims: [ 3, 640, 640 ] }
]
output [
  { name: "images" data_type: TYPE_FP32 dims: [ 3, 640, 640 ] }
]

parameters: {
  key: "normalize"
  value: { string_value: "true" }
}

